layout_spectrum: 0.3146938050787269
typography_spectrum: 0.027393887875103714
color:
  brandStrength: 0.32497406769064396
  lightness: 0.10107998994298943
  saturation: 0.3791589076287749
  rhythmicContrast: 0.9128955528332787
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
coverPrefs:
  filter: false
github: true
analytics:
  google: UA-31654273-4
author:
  name: The Spin Meister
  email: d@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b15880cf-beb8-408b-8b63-586dba6801a7.png
name: Speed Metal Custom
navigation:
  - name: News
    url: 'http://spinonthese.com/'
    type: external
  - name: Custom Wheels
    url: 'http://spinonthese.com/hey-fatboy'
    type: external
  - name: Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Lightning Gravel Adventure GX-1
    id: fe1a8c66-3328-4d0f-bb43-da709973d1af
    type: content
  - name: Grab Yourself a Bargain! Disc Road Racer DX-1
    id: 3d716eb5-9b63-473f-9ceb-407b156c22e4
    type: content
  - name: Lightning Road Race X-1
    id: 416601c8-a81d-42fe-908a-e325fc309124
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64353fed-4aea-45d9-be54-241756cb2c79.png
title: Titanium bike. Custom made.
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4ebec2b6-51e6-4643-adf9-63dbbe6dac81.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4ebec2b6-51e6-4643-adf9-63dbbe6dac81.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Speed Metal is custom crafted titanium made perfect for you and no other
  rider. From drawing board to your ultimate N+1 in as little as 6 weeks. Use
  these buttons to get in touch and let's get your best bike ever out of your
  head and onto my drawing board.
purpose:
  - type: phone
    url: 'tel:+441789459193'
    label: Call
  - type: contact
    url: 'mailto:spinfo@ridefullgas.com'
    label: Email
