typography_spectrum: 0.024953485321124444
color:
  brandStrength: 0.2402529585692515
  lightness: 0.6090710809316007
  saturation: 0.6479183933085365
  rhythmicContrast: 0.5743688156356168
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
layout_spectrum: 0.754928549267536
analytics:
  google: UA-31654273-4
author:
  name: The Spin Meister
  email: d@ridefullgas.com
  url: 'http://ridefullgas.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a86a2e68-6b8d-4e6b-86af-ac77bebbb034.png
name: Speed Metal Custom
navigation:
  - name: Custom Bikes
    id: 8ccc5dd4-50c8-41ac-baaa-8c39c10aa268
    type: content
  - name: News
    url: 'http://spinonthese.com/'
    type: external
  - name: Custom Wheels
    url: 'http://spinonthese.com/hey-fatboy'
    type: external
  - name: Shop
    url: 'http://ridefullgas.com/'
    type: external
  - name: Lightning GX-1
    id: fe1a8c66-3328-4d0f-bb43-da709973d1af
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64353fed-4aea-45d9-be54-241756cb2c79.png
title: Titanium bike. Custom made.
content: []
coverPrefs:
  filter: false
description: >-
  Speed Metal is custom crafted titanium made perfect for you and no other
  rider. From drawing board to your ultimate N+1 in as little as 6 weeks. Ready
  to build your dream ride? Let's get talking!
purpose:
  - type: phone
    url: 'tel:+441789459193'
    label: Gimme a call!
  - type: contact
    url: 'mailto:spinfo@ridefullgas.com'
    label: Mail me!
